### ISSUE TITLE
Training the Phenaki - RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by LuthandoMaqondo** [lucidrains/phenaki-pytorch#37]
I have created a notebook and pasted the training code from the README.md file so that I can experiment with training the model, but I encounter the following error when training the Phenaki. is there anything I'm doing wrong.

The same error emerges both on **_Google Colab_** and  **_AWS EC2 - p4d instance_** with 8 A100 GPUs.

Here's the error I getting:

```
<@beartype(phenaki_pytorch.phenaki_pytorch.Phenaki.forward) at 0x7fd70d61cf70> in forward(__beartype_object_94770277747520, __beartype_getrandbits, __beartype_get_violation, __beartype_conf, __beartype_func, *args, **kwargs)

[/content/phenaki-pytorch/phenaki_pytorch/phenaki_pytorch.py](https://localhost:8080/#) in forward(self, videos, texts, video_codebook_ids, video_frame_mask, text_embeds, cond_drop_prob, only_train_generator, only_train_critic)
    642         if not only_train_critic:
    643             loss = F.cross_entropy(
--> 644                 logits[mask_token_mask],
    645                 video_codebook_ids[mask_token_mask]
    646             )

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by 23Rj20** [comment]
how did you fix this error

**Comment by tzenmatt** [comment]
who is a legendary python coder here?

**Comment by LuthandoMaqondo** [comment]
> how did you fix this error

When you're setting up the Phenaki, you need to specify the correct number of ```num_tokens ``` in the MaskGit instance.
```
maskgit = MaskGit(
    num_tokens = 5000,  #This is the source of error if not set correctly for the corresponding cViViT.
    max_seq_len = 1024,
    dim = 512,
    dim_context = 768,
    depth = 6,
    unconditional = False
)

phenaki = Phenaki(
    cvivit = cvivit,
    maskgit = maskgit
).cuda()
```

I replaced the ```5000``` with ```codebook_size``` from ```cViViT```.  **_the error was gone_**.
